const ServiceUserActionTypes = {
  SET_SERVICEUSERS: "SET_SERVICEUSER",
  GET_SERVICEUSERS: "GET_SERVICEUSER",
  GET_SERVICEUSERS_FAILURE: "GET_SERVICEUSERS_FAILURE",
  CREATE_SERVICEUSER:"CREATE_SERVICEUSER",
};
export default ServiceUserActionTypes;
